### ISSUE TITLE
macOS Catalina 10.15.7 启动失败

### ISSUE THREAD

**Issue by tinytinycn** [xfangfang/Macast#1]
默认	08:37:15.038584+0800	Dock	LAUNCHING:0x0-0xe30e3 Macast foreground=0 bringForward=0 seed=1003 userActivityCount=0
默认	08:37:15.046447+0800	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Macast
默认	08:37:15.047483+0800	runningboardd	Resolved pid 5741 to [executable<Macast(501)>:5741]
默认	08:37:15.052589+0800	runningboardd	[executable<Macast(501)>:5741] This process will not be managed.
默认	08:37:15.052651+0800	runningboardd	Now tracking process: [executable<Macast(501)>:5741]
默认	08:37:15.053533+0800	runningboardd	Acquiring assertion targeting executable<Macast(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:131] with description <RBSAssertionDescriptor; uielement:5741; ID: 394-131-1398; target: 5741> attributes = {
    <RBSDomainAttribute: 0x7fb9a6d28eb0; domain: com.apple.launchservicesd; name: RoleUserInteractive; sourceEnvironment: 0x0>;
}
默认	08:37:15.053725+0800	runningboardd	Assertion 394-131-1398 (target:executable<Macast(501)>) will be created as active
默认	08:37:15.054653+0800	runningboardd	[executable<Macast(501)>:5741] Ignoring jetsam update because this process is not memory-managed
默认	08:37:15.054841+0800	runningboardd	[executable<Macast(501)>:5741] Ignoring resume because this process is not lifecycle managed
默认	08:37:15.054603+0800	runningboardd	Acquiring assertion targeting executable<Macast(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:131] with description <RBSAssertionDescriptor; uielement:5741; ID: 394-131-1399; target: 5741> attributes = {
    <RBSDomainAttribute: 0x7fb9a9308790; domain: com.apple.launchservicesd; name: RoleUserInteractive; sourceEnvironment: 0x0>;
}
默认	08:37:15.054954+0800	runningboardd	[executable<Macast(501)>:5741] Set darwin role to: UserInteractive
默认	08:37:15.055075+0800	runningboardd	[executable<Macast(501)>:5741] Ignoring GPU update because this process is not GPU managed
默认	08:37:15.055147+0800	runningboardd	Assertion 394-131-1399 (target:executable<Macast(501)>) will be created as active
默认	08:37:15.055305+0800	runningboardd	Finished acquiring assertion 394-131-1398 (target:executable<Macast(501)>)
默认	08:37:15.056363+0800	runningboardd	Finished acquiring assertion 394-131-1399 (target:executable<Macast(501)>)
默认	08:37:15.056385+0800	runningboardd	Invalidating assertion 394-131-1398 (target:executable<Macast(501)>) from originator 131
默认	08:37:15.112395+0800	Macast	FRONTLOGGING: version 1
默认	08:37:15.112437+0800	Macast	Registering, pid=5741
默认	08:37:15.113140+0800	Macast	CHECKIN: pid=5741
错误	08:37:15.118426+0800	tccd	Failed to copy signing info for 5741, responsible for file:///Applications/Macast.app/Contents/MacOS/Macast: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
默认	08:37:15.122836+0800	Macast	CHECKEDIN: pid=5741 asn=0x0-0xe30e3 foreground=0
默认	08:37:15.122548+0800	launchservicesd	CHECKIN:0x0-0xe30e3 5741 org.pythonmac.unspecified.Macast
默认	08:37:15.123708+0800	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Macast
默认	08:37:15.123460+0800	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier org.pythonmac.unspecified.Macast, type: 0: 0x7ff8312097b0 at /Applications/Macast.app
默认	08:37:15.124938+0800	Macast	Registered, pid=5741 ASN=0x0,0xe30e3
默认	08:37:15.125097+0800	Macast	Registered, pid=5741 cgConnectionID=62403
默认	08:37:15.126488+0800	Macast	BringForward: pid=5741 asn=0x0-0xe30e3 bringForward=0 foreground=0 uiElement=1 launchedByLS=1 modifiersCount=1 allDisabled=0
默认	08:37:15.126554+0800	Macast	BringFrontModifier: pid=5741 asn=0x0-0xe30e3 Modifier 0 hideAfter=0 hideOthers=0 dontMakeFrontmost=0 mouseDown=0/0 seed=0/0
默认	08:37:15.127088+0800	Macast	SignalReady: pid=5741 asn=0x0-0xe30e3
默认	08:37:15.128106+0800	Macast	SIGNAL: pid=5741 asn=0x0x-0x930019
默认	08:37:17.217293+0800	Macast	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(aevt,oapp handler=0x1000fffc0 isSys=NO) err=0/noErr
默认	08:37:17.217363+0800	Macast	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(aevt,odoc handler=0x1000fff90 isSys=NO) err=0/noErr
默认	08:37:17.217413+0800	Macast	OSErr AERemoveEventHandler(AEEventClass, AEEventID, AEEventHandlerUPP, Boolean)(GURL,GURL handler=0x1000fff60 isSys=NO) err=0/noErr
默认	08:37:17.311872+0800	Macast	Current system appearance, (HLTB: 1), (SLS: 0)
默认	08:37:17.319216+0800	Macast	Post-registration system appearance: (HLTB: 1)
默认	08:37:17.326909+0800	distnoted	register name: com.apple.xctest.FakeForceTouchDevice object: org.pythonmac.unspecified.Macast token: f4280 pid: 5741
默认	08:37:17.329972+0800	Macast	SetFrontProcess: asn=0x0-0xe30e3 options=1
默认	08:37:17.330605+0800	Macast	Received configuration update from daemon (initial)
默认	08:37:17.331079+0800	runningboardd	Acquiring assertion targeting executable<Macast(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:131] with description <RBSAssertionDescriptor; frontmost:5741; ID: 394-131-1400; target: 5741> attributes = {
    <RBSDomainAttribute: 0x7fb9a900d210; domain: com.apple.launchservicesd; name: RoleUserInteractiveFocal; sourceEnvironment: 0x0>;
}
默认	08:37:17.331232+0800	runningboardd	Assertion 394-131-1400 (target:executable<Macast(501)>) will be created as active
默认	08:37:17.333499+0800	Macast	SetFrontProcess: asn=0x0-0xe30e3 options=0
默认	08:37:17.333512+0800	runningboardd	Finished acquiring assertion 394-131-1400 (target:executable<Macast(501)>)
默认	08:37:17.334026+0800	runningboardd	[executable<Macast(501)>:5741] Ignoring jetsam update because this process is not memory-managed
默认	08:37:17.334512+0800	runningboardd	[executable<Macast(501)>:5741] Set darwin role to: UserInteractiveFocal
默认	08:37:17.335212+0800	runningboardd	[executable<Macast(501)>:5741] Ignoring GPU update because this process is not GPU managed
默认	08:37:17.339320+0800	Macast	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 1
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600002c06500
 (
    "<NSAquaAppearance: 0x600002c06300>",
    "<NSSystemAppearance: 0x600002c06380>"
)>
默认	08:37:17.352745+0800	distnoted	register name: com.apple.nsquiet_safe_quit_give_reason object: org.pythonmac.unspecified.Macast token: f428c pid: 5741
默认	08:37:17.418541+0800	hidd	Connection added: IOHIDEventSystemConnection uuid:B5DC2EC5-BA95-4703-BDA8-E80774850013 pid:5741 process:Macast type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) state:0x0 events:0 mask:0x0
默认	08:37:19.962233+0800	hidd	Connection removed: IOHIDEventSystemConnection uuid:B5DC2EC5-BA95-4703-BDA8-E80774850013 pid:5741 process:Macast type:Passive entitlements:0x0 caller:HIToolbox: ___GetIOHIDEventSystemClient_block_invoke + 26 attributes:(null) state:0x1 events:0 mask:0x0
默认	08:37:19.965898+0800	runningboardd	[executable<Macast(501)>:5741] Death sentinel fired!
默认	08:37:19.968040+0800	runningboardd	Invalidating assertion 394-131-1400 (target:executable<Macast(501)>) from originator 131
默认	08:37:19.973129+0800	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Macast, _appTrackingState = 2
默认	08:37:19.974764+0800	runningboardd	Invalidating assertion 394-131-1399 (target:executable<Macast(501)>) from originator 131
默认	08:37:20.070996+0800	runningboardd	Removing process: [executable<Macast(501)>:5741]
默认	08:37:20.071561+0800	runningboardd	Removing assertions for terminated process: [executable<Macast(501)>:5741]
错误	08:37:20.087471+0800	runningboardd	RBSStateCapture remove item called for untracked item 394-131-1400 (target:executable<Macast(501)>)
错误	08:37:20.087508+0800	runningboardd	RBSStateCapture remove item called for untracked item 394-131-1399 (target:executable<Macast(501)>)
默认	08:37:49.771044+0800	Dock	LAUNCHING:0x0-0xe40e4 Macast foreground=0 bringForward=0 seed=1005 userActivityCount=0
默认	08:37:49.780746+0800	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Macast
默认	08:37:49.783505+0800	runningboardd	Resolved pid 5745 to [executable<Macast(501)>:5745]
默认	08:37:49.785924+0800	runningboardd	[executable<Macast(501)>:5745] This process will not be managed.
默认	08:37:49.785964+0800	runningboardd	Now tracking process: [executable<Macast(501)>:5745]
默认	08:37:49.786633+0800	runningboardd	Acquiring assertion targeting executable<Macast(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:131] with description <RBSAssertionDescriptor; uielement:5745; ID: 394-131-1402; target: 5745> attributes = {
    <RBSDomainAttribute: 0x7fb9a93183b0; domain: com.apple.launchservicesd; name: RoleUserInteractive; sourceEnvironment: 0x0>;
}
默认	08:37:49.786801+0800	runningboardd	Assertion 394-131-1402 (target:executable<Macast(501)>) will be created as active
默认	08:37:49.787462+0800	runningboardd	[executable<Macast(501)>:5745] Ignoring jetsam update because this process is not memory-managed
默认	08:37:49.787676+0800	runningboardd	Acquiring assertion targeting executable<Macast(501)> from originator [daemon<com.apple.coreservices.launchservicesd>:131] with description <RBSAssertionDescriptor; uielement:5745; ID: 394-131-1403; target: 5745> attributes = {
    <RBSDomainAttribute: 0x7fb9a920ad10; domain: com.apple.launchservicesd; name: RoleUserInteractive; sourceEnvironment: 0x0>;
}
默认	08:37:49.787611+0800	runningboardd	[executable<Macast(501)>:5745] Ignoring resume because this process is not lifecycle managed
默认	08:37:49.787847+0800	runningboardd	[executable<Macast(501)>:5745] Set darwin role to: UserInteractive
默认	08:37:49.787883+0800	runningboardd	Assertion 394-131-1403 (target:executable<Macast(501)>) will be created as active
默认	08:37:49.787955+0800	runningboardd	[executable<Macast(501)>:5745] Ignoring GPU update because this process is not GPU managed
默认	08:37:49.788048+0800	runningboardd	Finished acquiring assertion 394-131-1402 (target:executable<Macast(501)>)
默认	08:37:49.788913+0800	runningboardd	Finished acquiring assertion 394-131-1403 (target:executable<Macast(501)>)
默认	08:37:49.788921+0800	runningboardd	Invalidating assertion 394-131-1402 (target:executable<Macast(501)>) from originator 131
默认	08:37:49.858886+0800	Macast	FRONTLOGGING: version 1
默认	08:37:49.858938+0800	Macast	Registering, pid=5745
默认	08:37:49.859646+0800	Macast	CHECKIN: pid=5745

**Comment by xfangfang** [comment]
@tinytinycn 感谢反馈，可能是软件签名问题？请尝试在terminal中运行
```
/Applications/Macast.app/Contents/MacOS/Macast
```
直接从命令行打开应用，这样会展示出应用内的log

**Comment by xfangfang** [comment]
@tinytinycn Thanks for your feedback，Maybe it's a software signature problem? 

Try running this in your terminal:

```
/Applications/Macast.app/Contents/MacOS/Macast
```

This helps opening the application directly from the command line, which will show the application logs

**Comment by tinytinycn** [comment]
# 以下是在terminal中执行命令后的异常日志
[tiny-MacBook-Pro:~ tinytinycn$ /Applications/Macast.app/Contents/MacOS/Macast
Traceback (most recent call last):
  File "/Applications/Macast.app/Contents/Resources/__boot__.py", line 411, in <module>
    _run()
  File "/Applications/Macast.app/Contents/Resources/__boot__.py", line 394, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/Macast.app/Contents/Resources/Macast.py", line 6, in <module>
    import rumps
  File "/Applications/Macast.app/Contents/Resources/lib/python3.7/rumps/__init__.py", line 25, in <module>
    from .rumps import (separator, debug_mode, alert, notification, application_support, timers, quit_application, timer,
  File "/Applications/Macast.app/Contents/Resources/lib/python3.7/rumps/rumps.py", line 13, in <module>
    import Foundation
  File "Foundation/__init__.pyc", line 9, in <module>
  File "CoreFoundation/__init__.pyc", line 9, in <module>
  File "objc/__init__.pyc", line 6, in <module>
  File "objc/_objc.pyc", line 14, in <module>
  File "objc/_objc.pyc", line 10, in __load
  File "imp.pyc", line 342, in load_dynamic
ImportError: dlopen(/Applications/Macast.app/Contents/Resources/lib/python3.7/lib-dynload/objc/_objc.so, 2): Symbol not found: __dyld_shared_cache_contains_path
  Referenced from: /Applications/Macast.app/Contents/Resources/lib/python3.7/lib-dynload/objc/_objc.so (which was built for Mac OS X 11.4)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Applications/Macast.app/Contents/Resources/lib/python3.7/lib-dynload/objc/_objc.so
2021-06-11 08:33:18.978 Macast[9100:526676] Macast Error
tiny-MacBook-Pro:~ tinytinycn$ python -V
Python 2.7.16

**Comment by xfangfang** [comment]
@tinytinycn 
It seems that the app compiled by 11.4 can't be used in  a lower system version. I compiled another one under MacOS 10.15 using GitHub action. Hope this can solve your problem. look forward to your reply

You can find ***Macast_v0.2.zip*** at the bottom of this page:

https://github.com/xfangfang/Macast/actions/runs/927837829

**Comment by tinytinycn** [comment]
yes, you are right! thank you!
