### ISSUE TITLE
插件无法正确安装

### ISSUE THREAD

**Issue by xvzhenduo** [xfangfang/Macast#106]
## Versions

- System: Windows 11 企业版
- System version: 21H2
- Processor architecture: x64
- APP version: v0.7

## Bug recurrence

1.右键单击托盘图标，进入设置>高级设置
2.选择任意一个插件并点击install

## Additional information
在配置文件目录下的renderer文件夹下有刚刚安装的插件但均为空文件
![image](https://user-images.githubusercontent.com/74353173/151113637-714ae995-3442-49b7-8b0a-a553b8aa7848.png)
(在不用代理和用v2rayN的时候都这样，顺便附上V2Ray的日志)

[v2rayN.txt](https://github.com/xfangfang/Macast/files/7939390/v2rayN.txt)

ps:我没有安装360等等杀毒软件，并且在我记录日志的时候已经关了Windows Defender防火墙，代理是全局代理，也没有什么问题，可以上GitHub

## Log

[macast.txt](https://github.com/xfangfang/Macast/files/7939387/macast.txt)

### PasteBoard
```
Macast Loading Language: zh_CN
{'Additional_Interfaces': [], 'ApplicationPort': 9389, 'Blocked_Interfaces': [], 'CheckUpdate': 1, 'DLNA_FriendlyName': 'Macast(xvzhenduo)', 'Macast_Protocol': 'DLNA Protocol', 'Macast_Renderer': 'MPV Renderer', 'MenubarIcon': 0, 'PlayerHW': 1, 'PlayerOntop': 1, 'PlayerPosition': 2, 'PlayerSize': 1, 'StartAtLogin': 0, 'USN': 'ed11e149-350e-45ef-af2a-f8c89734707a'}
<Load Plugin from live
Cannot find any plugin in live
<Load Plugin from potplayer
Cannot find any plugin in potplayer
<Load Plugin from web
Cannot find any plugin in web
<Load Plugin from nirvana
Cannot find any plugin in nirvana
using plugin: MPV Renderer
using plugin: DLNA Protocol
(2, 'RegDeleteValue', '系统找不到指定的文件。')
get update info error: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/xfangfang/Macast/releases/latest (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
INFO:cherrypy.error:[26/Jan/2022:14:27:54] ENGINE Set handler for console events.
ERROR:SSDPServer:add membership 192.168.0.102
INFO:cherrypy.error:[26/Jan/2022:14:27:54] ENGINE Started monitor thread 'SSDP_NOTIFY_THREAD'.
ERROR:SSDPServer:add membership 192.168.137.1
ERROR:SSDPServer:[WinError 10049] 在其上下文中，该请求的地址无效。
INFO:cherrypy.error:[26/Jan/2022:14:27:54] ENGINE Started monitor thread 'Autoreloader'.
INFO:cherrypy.error:[26/Jan/2022:14:27:54] ENGINE Bus STARTED
INFO:server:Server current run on port: 9389
ERROR:MPVRenderer:mpv ipc socket start connect
INFO:MPVRenderer:{'event': 'property-change', 'id': 1, 'name': 'volume', 'data': 100.0}
INFO:MPVRenderer:{'event': 'property-change', 'id': 3, 'name': 'pause', 'data': False}
INFO:cherrypy.access.1963868851848:127.0.0.1 - - [26/Jan/2022:14:28:02] "GET / HTTP/1.1" 200 26758 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
INFO:cherrypy.access.1963868851848:127.0.0.1 - - [26/Jan/2022:14:28:03] "GET /assets/element-ui@2.15.7.css HTTP/1.1" 200 241586 "http://127.0.0.1:9389/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
INFO:cherrypy.access.1963868851848:127.0.0.1 - - [26/Jan/2022:14:28:03] "GET /assets/vue-resource@1.5.3.js HTTP/1.1" 200 15073 "http://127.0.0.1:9389/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
INFO:cherrypy.access.1963868851848:127.0.0.1 - - [26/Jan/2022:14:28:03] "GET /assets/element-ui@2.15.7.js HTTP/1.1" 200 583800 "http://127.0.0.1:9389/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
INFO:cherrypy.access.1963868851848:127.0.0.1 - - [26/Jan/2022:14:28:03] "GET /assets/vue@2.6.14.js HTTP/1.1" 200 94156 "http://127.0.0.1:9389/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
INFO:cherrypy.access.1963868851848:127.0.0.1 - - [26/Jan/2022:14:28:03] "GET /api?query=plugin-info HTTP/1.1" 200 651 "http://127.0.0.1:9389/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
INFO:cherrypy.access.1963868851848:127.0.0.1 - - [26/Jan/2022:14:28:03] "GET /api?query=log HTTP/1.1" 200 1810 "http://127.0.0.1:9389/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
INFO:cherrypy.access.1963868851848:127.0.0.1 - - [26/Jan/2022:14:28:03] "GET /assets/fonts/element-icons.woff HTTP/1.1" 200 28200 "http://127.0.0.1:9389/assets/element-ui@2.15.7.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
INFO:cherrypy.access.1963868851848:127.0.0.1 - - [26/Jan/2022:14:28:03] "GET /assets/icon.ico HTTP/1.1" 200 36735 "http://127.0.0.1:9389/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
INFO:cherrypy.access.1963868851848:127.0.0.1 - - [26/Jan/2022:14:28:03] "GET /assets/avatar.png HTTP/1.1" 200 4097 "http://127.0.0.1:9389/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
ERROR:Protocol:download plugin error: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /xfangfang/Macast-plugins/main/nirvana/nirvana.py (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
INFO:cherrypy.error:[26/Jan/2022:14:28:13] ENGINE Bus STOPPING
INFO:cherrypy.error:[26/Jan/2022:14:28:13] ENGINE HTTP Server cherrypy._cpnative_server.CPHTTPServer(('0.0.0.0', 9389)) shut down
INFO:cherrypy.error:[26/Jan/2022:14:28:13] ENGINE Stopped thread 'SSDP_NOTIFY_THREAD'.
ERROR:SSDPServer:drop membership 192.168.0.102
ERROR:SSDPServer:drop membership 192.168.137.1
INFO:main:service_stop
INFO:main:renderer_av_stop
INFO:MPVRenderer:stoping mpv and mpv ipc
ERROR:MPVRenderer:[Errno 10] No child processes
ERROR:MPVRenderer:mpv ipc stopped
INFO:MPVRenderer:mpv stopped
INFO:cherrypy.error:[26/Jan/2022:14:28:13] ENGINE Stopped thread 'Autoreloader'.
INFO:cherrypy.error:[26/Jan/2022:14:28:13] ENGINE Removed handler for console events.
INFO:cherrypy.error:[26/Jan/2022:14:28:13] ENGINE Bus STOPPED
INFO:cherrypy.error:[26/Jan/2022:14:28:13] ENGINE Bus EXITING
INFO:cherrypy.error:[26/Jan/2022:14:28:13] ENGINE Waiting for child threads to terminate...
INFO:cherrypy.error:[26/Jan/2022:14:28:13] ENGINE Bus EXITED
INFO:cherrypy.error:[26/Jan/2022:14:28:13] ENGINE Waiting for thread ('CP Server Thread-5',).
INFO:cherrypy.access.1963868851848:127.0.0.1 - - [26/Jan/2022:14:28:13] "POST /api HTTP/1.1" 200 43 "http://127.0.0.1:9389/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
INFO:cherrypy.error:[26/Jan/2022:14:28:13] ENGINE Re-spawning C:\Program Files\Macast\Macast-Windows-v0.7-debug.exe C:\Program Files\Macast\Macast-Windows-v0.7-debug.exe
Macast Loading Language: zh_CN
{'Additional_Interfaces': [], 'ApplicationPort': 9389, 'Blocked_Interfaces': [], 'CheckUpdate': 1, 'DLNA_FriendlyName': 'Macast(xvzhenduo)', 'Macast_Protocol': 'DLNA Protocol', 'Macast_Renderer': 'MPV Renderer', 'MenubarIcon': 0, 'PlayerHW': 1, 'PlayerOntop': 1, 'PlayerPosition': 2, 'PlayerSize': 1, 'StartAtLogin': 0, 'USN': 'ed11e149-350e-45ef-af2a-f8c89734707a'}
<Load Plugin from live
Cannot find any plugin in live
<Load Plugin from potplayer
Cannot find any plugin in potplayer
<Load Plugin from web
Cannot find any plugin in web
<Load Plugin from nirvana
Cannot find any plugin in nirvana
using plugin: MPV Renderer
using plugin: DLNA Protocol
(2, 'RegDeleteValue', '系统找不到指定的文件。')
get update info error: HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/xfangfang/Macast/releases/latest (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))
ERROR:SSDPServer:add membership 192.168.0.102
INFO:cherrypy.error:[26/Jan/2022:14:28:15] ENGINE Started monitor thread 'SSDP_NOTIFY_THREAD'.
ERROR:SSDPServer:add membership 192.168.137.1
ERROR:SSDPServer:[WinError 10049] 在其上下文中，该请求的地址无效。
INFO:cherrypy.error:[26/Jan/2022:14:28:15] ENGINE Started monitor thread 'Autoreloader'.
INFO:cherrypy.error:[26/Jan/2022:14:28:15] ENGINE Bus STARTED
INFO:server:Server current run on port: 9389
INFO:cherrypy.access.2279345851464:127.0.0.1 - - [26/Jan/2022:14:28:15] "GET /assets/avatar.png HTTP/1.1" 200 4097 "http://127.0.0.1:9389/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36"
ERROR:cherrypy.error.2279345851464:[26/Jan/2022:14:28:15] NATIVE_ADAPTER Traceback (most recent call last):
  File "cherrypy\_cpnative_server.py", line 91, in respond
  File "cherrypy\_cpnative_server.py", line 117, in send_response
  File "cheroot\server.py", line 1146, in write
  File "cheroot\makefile.py", line 438, in write
  File "cheroot\makefile.py", line 36, in write
  File "cheroot\makefile.py", line 45, in _flush_unlocked
  File "socket.py", line 607, in write
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。

ERROR:MPVRenderer:mpv ipc socket start connect
INFO:MPVRenderer:{'event': 'property-change', 'id': 1, 'name': 'volume', 'data': 100.0}
INFO:MPVRenderer:{'event': 'property-change', 'id': 3, 'name': 'pause', 'data': False}



```

**Comment by xfangfang** [comment]
感谢详细反馈，如果您的代理工作在使用浏览器时工作正常的话，问题可能是由两方面导致的：

1. 虽然能访问github，但是因为网络问题，您还是无法不通过代理访问插件下载地址：[示例](https://raw.githubusercontent.com/xfangfang/Macast-plugins/main/info.json)

2. 因为Windows平台的历史遗留问题，代理软件没有正确区分代理协议。


解决办法：

1. 让代理软件正常工作，这一点我只知道在clash上可以通过打开Specify Protocol选项来适配。[快速上手](https://github.com/xfangfang/Macast/wiki/快速上手#快速上手)
2. 手动下载插件：[如何手动安装插件](https://github.com/xfangfang/Macast/wiki/快速上手#如何手动安装插件)

**Comment by xvzhenduo** [comment]
插件我已经手动安装了，不过应该是第二个问题吧，因为看v2ray的日志第十行和第十一行的HTTP request是\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03y**J`A5\xe7\x9e\xe7C\xe2\xed\xfc<Fnx\xe9)\xf3\xd0С\u0380\xf9KLF\x9em I\xae\x16\xcc\x12FcN_ٓ<\x9c\xad˸\xf4\x96\xbb\xc0\x10Ժg\xe2Z\xe1\x16\r\xb8MC\x00V\x13\x02\x13\x03\x13\x01\xc0,\xc00\xc0+\xc0/̨̩\x00\x9f\x00\x9e̪\xc0\xaf\xc0\xad\xc0\xae\xc0\xac\xc0$\xc0(\xc0#\xc0'\xc0

**Comment by xfangfang** [comment]
@xvzhenduo应该两个问题都存在
根据前面说的：
> (在不用代理和用v2rayN的时候都这样，顺便附上V2Ray的日志)
 
推测应该是访问不到github导致的，或者访问太慢超时了，你可以访问我前面发的那个“示例”试试，如果能“直接”访问，那就可以直接安装。

代理的问题，只在windows上出现，这个我也不大了解，貌似其他软件也会出现类似的兼容问题，应该是代理软件的问题。

相关issue：https://github.com/Fndroid/clash_for_windows_pkg/issues/1787

之后或许会尝试修复一下这个问题，感兴趣也可以提pr帮助修复一下

**Comment by xvzhenduo** [comment]
github肯定是可以访问到的，而且速度挺快的，
![image](https://user-images.githubusercontent.com/74353173/151120458-02991d51-82f5-4635-862b-ed69d730e671.png)
可能是应用并没有走代理
可以考虑在下载完插件时判断一下插件的大小，如果为空，请求hub.fastgit.org，github.com.cnpmjs.org这两个镜像或者用github.91chi.fun加速

**Comment by xfangfang** [comment]
如果不开代理能正常访问github，那就不会出现下载完成后是一个空文件的情况，这和前面您的描述不符，建议有空再测试看看。

为了稳定性应该不会切换到第三方服务去，之后准备做一个切换插件仓库的功能，这样国内用户就可以选择类似gitee这样的备用仓库来下载。
