### ISSUE TITLE
[BUG] macast-gui fail to start if ~/.config/Macast/ don't exist

### ISSUE THREAD

**Issue by FabioLolix** [xfangfang/Macast#130]
## Versions

- System: Arch Linux
- System version: latest
- Processor architecture: x86_64/amd64 
- APP version: 0.7.r21.g8f9d99d, latest git commit from improved AUR pkgbuild

## Bug recurrence

launch macast-gui from terminal

$ macast-gui

## Additional information

Fixed by creating ~/.config/Macast/ manually

### PasteBoard
```
$ LANG=C macast-gui
Unhandled error
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/macast/utils.py", line 546, in wrapper
    return fun(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/macast/macast.py", line 603, in gui
    Setting.setup_logger()
  File "/usr/lib/python3.10/site-packages/macast/utils.py", line 430, in setup_logger
    handlers=[logging.StreamHandler(), logging.FileHandler(log_file, mode='w', encoding='utf-8')]
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/home/fabio/.config/Macast/macast.log'

```

**Comment by xfangfang** [comment]
I don't maintain the AUR package, but I probably know what the problem is.

There is a problem with the current dev branch. For new users, the configuration file directory is not created correctly. This problem has been solved in another branch(dev_test). I will deal with this problem as soon as possible.

At the same time, a simple way to fix this is to manually create the configuration file directory.

```shell
mkdir ~/.config/Macast/
```

**Comment by FabioLolix** [comment]
> There is a problem with the current dev branch

Yes, I'm using the dev branch

> mkdir ~/.config/Macast/

That's what I've done :)

**Comment by icepie** [comment]
maybe change to the main branch will fix it

**Comment by FabioLolix** [comment]
@icepie I have send you a macast-git revisioned pkgbuild 3 days ago

**Comment by icepie** [comment]
Thanks! I get it and apply it. 

And if run `setup.py` with `--skip-build` parameter will ignore building the `i18n` files, so I delete this.

> @icepie I have send you a macast-git revisioned pkgbuild 3 days ago

**Comment by FabioLolix** [comment]
> And if run setup.py with --skip-build parameter will ignore building the i18n files, so I delete this.

OK, didn't noticed that, so you can remove the whole build() then, would you like to write in the pkgbuild that separating build() and package() have this issue? So you wont be botherd in the future

**Comment by icepie** [comment]
> > And if run setup.py with --skip-build parameter will ignore building the i18n files, so I delete this.
> 
> OK, didn't noticed that, so you can remove the whole build() then, would you like to write in the pkgbuild that separating build() and package() have this issue? So you wont be botherd in the future

That's an interesting question...I separated build() but still not to compile *.mo files
