### ISSUE TITLE
[BUG]  Ubuntu20.04 安装成功 点击不运行

### ISSUE THREAD

**Issue by 1040190901** [xfangfang/Macast#16]
Traceback (most recent call last):
  File "Macast.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "macast/__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "macast/gui.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pystray/__init__.py", line 48, in <module>
  File "pystray/__init__.py", line 40, in backend
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pystray/_appindicator.py", line 22, in <module>
  File "gi/__init__.py", line 129, in require_version
ValueError: Namespace AppIndicator3 not available
[25791] Failed to execute script 'Macast' due to unhandled exception!

**Comment by xfangfang** [comment]
please refer to: https://gitee.com/xfangfang/Macast/issues/I462AN
