### ISSUE TITLE
[BUG] Launch error

### ISSUE THREAD

**Issue by Tobi1chi** [xfangfang/Macast#168]
## Versions

- System: MacOS
- System version: 12.3.1
- Processor architecture: Intel
- APP version: v0.7

## Bug recurrence

100% to repeat, the error will happen if I launch the app.
THe app notices me to see the py2app website for debugging launch issues.

### PasteBoard
```
<Load Plugin from nirvana
title     : NVA Protocol
protocol  : NVAProtocol
platform  : darwin,win32,linux
version   : 0.31
host_version: 0.7
author    : xfangfang
desc      : NVA protocol support for Macast. Known as "哔哩必连" v0.31: Fix proxy related problems.
Load plugin NVAProtocol done />

<Load Plugin from web
title     : Web Renderer
renderer  : WebRenderer
platform  : darwin,linux,win32
version   : 0.2
host_version: 0.7
author    : xfangfang
desc      : Using web browser as DLNA media renderer, This plugin can be used to download media files or get some m3u8 played.
Load plugin WebRenderer done />

<Load Plugin from potplayer
title     : PotPlayer Renderer
renderer  : PotplayerRenderer
platform  : win32
version   : 0.4
host_version: 0.7
author    : xfangfang
desc      : PotPlayer support for Macast, this is a simple plugin that only supports play and stop.
No module named 'win32api'
<Load Plugin from iina
title     : IINA Renderer
renderer  : IINARenderer
platform  : darwin
version   : 0.31
host_version: 0.7
author    : xfangfang
desc      : IINA support for Macast. Because iina is developed based on MPV, this plugin's experience is similar to the built-in MPV renderer.
Load plugin IINARenderer done />

<Load Plugin from live
title     : Live Renderer
renderer  : LiveRenderer
platform  : win32,darwin,linux
version   : 0.2
host_version: 0.7
author    : dushan555
desc      : Live support for Macast,It developed based on MPVRenderer,Can be used to watch live TV.
Load plugin LiveRenderer done />

<Load Plugin from nirvana
title     : NVA Protocol
protocol  : NVAProtocol
platform  : darwin,win32,linux
version   : 0.31
host_version: 0.7
author    : xfangfang
desc      : NVA protocol support for Macast. Known as "哔哩必连" v0.31: Fix proxy related problems.
Load plugin NVAProtocol done />

using plugin: NVA Protocol
using plugin: NVA Protocol
Traceback (most recent call last):
  File "/Applications/Macast.app/Contents/Resources/__boot__.py", line 440, in <module>
    _run()
  File "/Applications/Macast.app/Contents/Resources/__boot__.py", line 394, in _run
    exec(compile(source, path, "exec"), globals(), globals())
  File "/Applications/Macast.app/Contents/Resources/Macast.py", line 60, in <module>
    gui(lang=_)
  File "/Applications/Macast.app/Contents/Resources/lib/python3.9/macast/macast.py", line 510, in gui
    Macast(renderer, protocol, lang).start()
  File "/Applications/Macast.app/Contents/Resources/lib/python3.9/macast/macast.py", line 216, in __init__
    self.build_app_menu(),
  File "/Applications/Macast.app/Contents/Resources/lib/python3.9/macast/macast.py", line 231, in build_app_menu
    self.setting_menuitem = MenuItem(_("Setting"), children=self.build_setting_menu())
  File "/Applications/Macast.app/Contents/Resources/lib/python3.9/macast/macast.py", line 312, in build_setting_menu
    player_settings = self.service.renderer.renderer_setting.build_menu()
AttributeError: 'NVAProtocol' object has no attribute 'renderer_setting'
2023-04-20 10:11:45.225 Macast[64838:7752400] Launch error
2023-04-20 10:11:45.225 Macast[64838:7752400] Launch error
See the py2app website for debugging launch issues
```

**Comment by xfangfang** [comment]
@Tobi1chi 
It looks like there was a problem with the plugins, I saw the NVA plugin load twice, which should not have happened. 

If you don't know how to handle this issue, just delete all plugins and then download the required plugins again.

**Comment by Tobi1chi** [comment]
@xfangfang 
Thanks a lot for your reply.
I could not find any file named NVA Protocol. So I want to ask where can I find all of the plugins.
Also, could you provide the source of those necessary plugins?

**Comment by xfangfang** [comment]
https://github.com/xfangfang/Macast/wiki/FAQ#where-is-the-configuration-file-located

https://github.com/xfangfang/Macast-plugins

**Comment by Tobi1chi** [comment]
```
a20201014341@Origa3mi-sama ~ % cd ~$HOME/Library/Application\ Support/Macast/
cd: no such file or directory: /Users/a20201014341/Users/a20201014341/Library/Application Support/Macast/
a20201014341@Origa3mi-sama ~ % $HOME/Library/Application\ Support/Macast/
zsh: permission denied: /Users/a20201014341/Library/Application Support/Macast/
```
What does this mean?

**Comment by xfangfang** [comment]
@Tobi1chi 

I think you are not familiar with shell command. Try this one:

```shell
open $HOME/Library/Application\ Support/Macast/
```

**Comment by Tobi1chi** [comment]
@xfangfang 
You are right, but I'm trying to do better! (I never use this before, sry)
Now the issue is done. Thanks sooo much! :)
