### ISSUE TITLE
[BUG] arch 系统无法正常使用

### ISSUE THREAD

**Issue by htqx** [xfangfang/Macast#184]
### Linux
Linux arch-pc-lv3 6.11.4-arch2-1 #1 SMP PREEMPT_DYNAMIC Sun, 20 Oct 2024 18:20:12 +0000 x86_64 GNU/Linux

一开始使用macast-bin 包，看不到右下角图标，更换 macast-git 包，显示图标，但是如法进入设置，以前会弹出浏览器的。

可以在手机上看到投屏端口，但是选择没有效果，不会弹出 mpv，设置 dlna 一样无法使用。

>macast-gui
INFO: [2024-10-26 16:41:00,803] - Utils/setup_logger/MainThread|133174467058560[line:433] - Using log level: INFO, 20
INFO: [2024-10-26 16:41:00,803] - Utils/setup_logger/MainThread|133174467058560[line:434] - Load Setting: {'Additional_Interfaces': [], 'ApplicationPort': 57059, 'Blocked_Interfaces': [], 'CheckUpdate': 1, 'DLNA_FriendlyName': 'Macast(arch-pc-lv3)', 'Macast_Log': 'INFO', 'Macast_Protocol': 'NVA Protocol', 'Macast_Renderer': 'Live Renderer', 'Macast_Setting_Port': 37269, 'Macast_Tool': [], 'MenubarIcon': 0, 'PlayerDefaultVolume': 100, 'PlayerHW': 1, 'PlayerOntop': 1, 'PlayerPosition': 4, 'PlayerSize': 4, 'StartAtLogin': 0, 'USN': '884fac2f-dd21-4285-88b3-3b5c9123c30c'}
INFO: [2024-10-26 16:41:00,803] - server/_run/SETTING_THREAD|133174212429504[line:247] - Start macast setting http server at http://localhost:37269
INFO: [2024-10-26 16:41:00,803] - main/get_lang/MainThread|133174467058560[line:588] - Macast Loading Language: zh_CN
INFO: [2024-10-26 16:41:00,804] - Utils/load/MainThread|133174467058560[line:90] - Load Setting
INFO: [2024-10-26 16:41:00,808] - main/load_from_file/MainThread|133174467058560[line:83] - ==========< Load Plugin from live
INFO: [2024-10-26 16:41:00,808] - LiveRenderer/<module>/MainThread|133174467058560[line:36] - live /home/htqx/.config/Macast/renderer/macast_live.m3u8
INFO: [2024-10-26 16:41:00,808] - main/load_from_file/MainThread|133174467058560[line:88] - title: Live Renderer
renderer: LiveRenderer
platform: win32,darwin,linux
version: 0.2
host_version: 0.7
author: dushan555
desc: Live support for Macast,It developed based on MPVRenderer,Can be used to watch live TV.
Load plugin LiveRenderer done />

INFO: [2024-10-26 16:41:00,809] - main/load_from_file/MainThread|133174467058560[line:83] - ==========< Load Plugin from nirvana
INFO: [2024-10-26 16:41:00,809] - main/load_from_file/MainThread|133174467058560[line:94] - title: NVA Protocol
protocol: NVAProtocol
platform: darwin,win32,linux
version: 0.31
host_version: 0.7
author: xfangfang
desc: NVA protocol support for Macast. Known as "哔哩必连" v0.31: Fix proxy related problems.
Load plugin NVAProtocol done />
....

INFO: [2024-10-26 16:43:04,499] - Protocol/call/CP Server Thread-15|133173413414592[line:603] - NirvanaControl_GetPlayInfo {'Params': None}
INFO: [2024-10-26 16:43:04,499] - Protocol/call/CP Server Thread-15|133173413414592[line:621] - res: {'Content': ''}
192.168.3.225 - - [26/Oct/2024:16:43:04] "POST /NirvanaControl/action HTTP/1.1" 200 276 "" "Linux/3.0.0 UPnP/1.0 Platinum/1.0.5.13"

**Comment by htqx** [comment]
无法弹出mpv 窗口  

```
723475840[line:108] - text: CCTV-3 data: http://117.148.179.160/PLTV/88888888/224/3221231682/index.m3u8
ERROR: [2024-11-01 15:01:35,821] - LiveRenderer/renderer/MainThread|128987723475840[line:95] - Unable to find an available renderer.
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pystray/_base.py", line 328, in inner
    callback(self)
  File "/usr/lib/python3.12/site-packages/pystray/_base.py", line 453, in __call__
    return self._action(icon, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/macast/gui.py", line 107, in _pystrayCallback
    self.callback(self)
  File "/home/htqx/.config/Macast/renderer/live.py", line 109, in on_start_click
    self.renderer.set_media_title(item.text)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'set_media_title'
```

**Comment by krishuang08** [comment]
你好请问你的这个问题解决了吗，我也无法弹出mpv
