### ISSUE TITLE
[BUG] Ubuntu failed to launch, do I use a wrong Python version? Ubuntu无法启动，是Python版本问题吗？

### ISSUE THREAD

**Issue by peacemo** [xfangfang/Macast#37]
## Versions

- System: Ubuntu
- System version: 20.04 LTS
- Processor architecture: amd64
- APP version: 0.5

## Bug recurrence

启动失败，Terminal报错。

Failed to launch, and print some lines in terminal. 

## Additional information

使用deb包安装的此软件的0.5版本，发现启动的时候汇报错，所以下载了源码，在启动的时候发现有一些依赖包没有安装上，包括`cherrypy`, `pystray`。在pip安装好所有的依赖包之后成功启动，但是使用Terminal启动依然会报错，Terminal使用的Python版本与我自己编译时使用的版本相同。

I installed the version 0.5 via `.deb` file, and it failed to launch while I started it. Then I downloaded the source code to build. Find out there are some Python dependencies missing including `cherrypy`, `pystray`,  ect. It worked after I fixed the dependency error, but I still can't launch it from the installation APP. 

## Log

Starting Macast from terminal to get logs.

### MacOS

run this in your terminal:
```
/Applications/Macast.app/Contents/MacOS/Macast
```

### Windows

download debug version of this application: [Download link](https://github.com/xfangfang/Macast/releases/latest)

### Linux

```
python Macast.py
```

### PasteBoard
```
Traceback (most recent call last):
  File "Macast.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "macast/__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "macast/gui.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pystray/__init__.py", line 48, in <module>
  File "pystray/__init__.py", line 40, in backend
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pystray/_appindicator.py", line 22, in <module>
  File "gi/__init__.py", line 129, in require_version
ValueError: Namespace AppIndicator3 not available
[9915] Failed to execute script 'Macast' due to unhandled exception!

```

**Comment by xfangfang** [comment]
linux需要下载最新测试版本：https://github.com/xfangfang/Macast/actions/runs/1174316000
ubuntu需要安装libappindicator3-dev依赖
其他linux信息请参考：https://github.com/xfangfang/Macast/wiki/Installation#linux

**Comment by xfangfang** [comment]
如果从源码运行 安装依赖请运行 pip -r requirements/common.txt  
安装的pystray 和 pyperclip 是经过我修改的，官方版本因为太久没更新或者不适合pyinstaller打包所以会有点问题的。

**Comment by peacemo** [comment]
The build/beta version works well. Thanx.

**Comment by peacemo** [comment]
> linux需要下载最新测试版本：https://github.com/xfangfang/Macast/actions/runs/1174316000
> ubuntu需要安装libappindicator3-dev依赖
> 其他linux信息请参考：https://github.com/xfangfang/Macast/wiki/Installation#linux

The build/beta version works well. Thanx.
