### ISSUE TITLE
[BUG] 无法运行

### ISSUE THREAD

**Issue by zqzess** [xfangfang/Macast#90]
## Versions

- System: win11
- System version: 21H2
- Processor architecture: X64
- APP version: 0.35

## Bug recurrence
无法运行

## Log

```
{'ApplicationPort': 1068, 'CheckUpdate': 1, 'DLNA_FriendlyName': 'Macast(DESKTOP-HVETC9J)', 'DLNA_Renderer': 'Default', 'MenubarIcon': 0, 'PlayerHW': 1, 'PlayerHW_Force': 1, 'PlayerSize_Auto': 2, 'StartAtLogin': 0, 'USN': 'a5cc293d-f7fd-46ee-ac16-f45205a52e5d'}
Load renderer MPVRenderer done
using renderer: Default
[WinError 2] 系统找不到指定的文件。
sendCommand: 'NoneType' object has no attribute 'send_bytes'
[Errno 10] No child processes
INFO:main:service_start
ERROR:SSDPServer:add membership 192.168.31.30
ERROR:SSDPServer:add membership 192.168.137.1
ERROR:SSDPServer:[WinError 10049] 在其上下文中，该请求的地址无效。
INFO:cherrypy.error:[30/Oct/2021:13:08:47] ENGINE Started monitor thread 'Autoreloader'.
INFO:cherrypy.error:[30/Oct/2021:13:08:47] ENGINE Started monitor thread 'SSDP_NOTIFY_THREAD'.
ERROR:cherrypy.error:[30/Oct/2021:13:08:47] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "c:\users\zqzes\appdata\local\programs\python\python37\lib\site-packages\cherrypy\process\wspbus.py", line 268, in start
    self.publish('start')
  File "c:\users\zqzes\appdata\local\programs\python\python37\lib\site-packages\cherrypy\process\wspbus.py", line 248, in publish
    raise exc
cherrypy.process.wspbus.ChannelFailures: OSError("No socket could be created -- (('0.0.0.0', 1068): [WinError 10013] 以 一种访问权限不允许的方式做了一个访问套接字的尝试。)")

INFO:cherrypy.error:[30/Oct/2021:13:08:47] ENGINE Bus STOPPING
INFO:cherrypy.error:[30/Oct/2021:13:08:47] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 1068)) already shut down
INFO:main:service_stop
INFO:MPVRenderer:stoping mpv and mpv ipc
ERROR:MPVRenderer:sendCommand: 'NoneType' object has no attribute 'send_bytes'
ERROR:MPVRenderer:[Errno 10] No child processes
ERROR:MPVRenderer:mpv ipc socket start connect
ERROR:MPVRenderer:mpv ipc socket reconnecting: [WinError 2] 系统找不到指定的文件。
INFO:main:tag_name: v0.65
ERROR:MPVRenderer:mpv restarting
INFO:cherrypy.error:[30/Oct/2021:13:08:48] ENGINE Stopped thread 'Autoreloader'.
INFO:cherrypy.error:[30/Oct/2021:13:08:48] ENGINE Stopped thread 'Autoreloader'.
INFO:cherrypy.error:[30/Oct/2021:13:08:48] ENGINE Removed handler for console events.
INFO:cherrypy.error:[30/Oct/2021:13:08:48] ENGINE Removed handler for console events.
INFO:cherrypy.error:[30/Oct/2021:13:08:48] ENGINE Stopped thread 'SSDP_NOTIFY_THREAD'.
INFO:cherrypy.error:[30/Oct/2021:13:08:48] ENGINE Stopped thread 'SSDP_NOTIFY_THREAD'.
ERROR:SSDPServer:drop membership 192.168.31.30
ERROR:SSDPServer:drop membership 192.168.137.1
INFO:cherrypy.error:[30/Oct/2021:13:08:48] ENGINE Bus STOPPED
INFO:cherrypy.error:[30/Oct/2021:13:08:48] ENGINE Bus STOPPED
INFO:cherrypy.error:[30/Oct/2021:13:08:48] ENGINE Bus EXITING
INFO:cherrypy.error:[30/Oct/2021:13:08:48] ENGINE Bus EXITING
INFO:cherrypy.error:[30/Oct/2021:13:08:48] ENGINE Bus EXITED
```

**Comment by xfangfang** [comment]
可以尝试手动修改配置文件中的端口参数为0，这个问题收到了几个windows用户反馈了，感觉是windows的某些配置导致的默认端口号无法使用。
配置文件在：%HOMEPATH%\AppData\Local\xfangfang\Macast

**Comment by zqzess** [comment]
可以运行了，但是服务无法启动
```
{'ApplicationPort': 1067, 'CheckUpdate': 1, 'DLNA_FriendlyName': 'Macast(DESKTOP-HVETC9J)', 'DLNA_Renderer': 'Default', 'MenubarIcon': 0, 'PlayerHW': 1, 'PlayerHW_Force': 1, 'PlayerSize_Auto': 2, 'StartAtLogin': 0, 'USN': 'a5cc293d-f7fd-46ee-ac16-f45205a52e5d'}
Load renderer MPVRenderer done
using renderer: Default
sendCommand: 'NoneType' object has no attribute 'send_bytes'
[Errno 10] No child processes

C:\Users\zqzes>macast-gui
{'ApplicationPort': 20000, 'CheckUpdate': 1, 'DLNA_FriendlyName': 'Macast(DESKTOP-HVETC9J)', 'DLNA_Renderer': 'Default', 'MenubarIcon': 0, 'PlayerHW': 1, 'PlayerHW_Force': 1, 'PlayerSize_Auto': 2, 'StartAtLogin': 0, 'USN': 'a5cc293d-f7fd-46ee-ac16-f45205a52e5d'}
Load renderer MPVRenderer done
using renderer: Default
ERROR:SSDPServer:add membership 192.168.31.30
ERROR:SSDPServer:add membership 192.168.137.1
ERROR:SSDPServer:[WinError 10049] 在其上下文中，该请求的地址无效。
ERROR:MPVRenderer:[WinError 2] 系统找不到指定的文件。
INFO:MPVRenderer:mpv stopped
INFO:cherrypy.error:[30/Oct/2021:14:37:33] ENGINE Serving on http://0.0.0.0:20000
INFO:main:service_start
INFO:cherrypy.error:[30/Oct/2021:14:37:33] ENGINE Started monitor thread 'Autoreloader'.
INFO:cherrypy.error:[30/Oct/2021:14:37:33] ENGINE Started monitor thread 'SSDP_NOTIFY_THREAD'.
INFO:cherrypy.error:[30/Oct/2021:14:37:33] ENGINE Bus STARTED
INFO:main:Server current run on port: 20000
ERROR:MPVRenderer:mpv ipc socket start connect
ERROR:MPVRenderer:mpv ipc socket reconnecting: [WinError 2] 系统找不到指定的文件。
INFO:main:tag_name: v0.65
ERROR:MPVRenderer:mpv ipc socket start connect
ERROR:MPVRenderer:mpv ipc socket reconnecting: [WinError 2] 系统找不到指定的文件。
ERROR:MPVRenderer:mpv restarting
INFO:MPVRenderer:mpv starting
ERROR:MPVRenderer:[WinError 2] 系统找不到指定的文件。
INFO:MPVRenderer:mpv stopped
ERROR:MPVRenderer:mpv ipc socket start connect
ERROR:MPVRenderer:mpv ipc socket reconnecting: [WinError 2] 系统找不到指定的文件。
ERROR:MPVRenderer:mpv ipc socket start connect
ERROR:MPVRenderer:mpv ipc socket reconnecting: [WinError 2] 系统找不到指定的文件。
ERROR:MPVRenderer:mpv restarting
INFO:MPVRenderer:mpv starting
ERROR:MPVRenderer:[WinError 2] 系统找不到指定的文件。
INFO:MPVRenderer:mpv stopped
ERROR:MPVRenderer:mpv ipc socket start connect
ERROR:MPVRenderer:mpv ipc socket reconnecting: [WinError 2] 系统找不到指定的文件。
ERROR:MPVRenderer:mpv ipc socket start connect
ERROR:MPVRenderer:mpv ipc socket reconnecting: [WinError 2] 系统找不到指定的文件。
ERROR:MPVRenderer:mpv restarting
ERROR:MPVRenderer:mpv cannot start
INFO:cherrypy.error:[30/Oct/2021:14:37:36] ENGINE Bus STOPPING
INFO:cherrypy.error:[30/Oct/2021:14:37:36] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 20000)) shut down
INFO:cherrypy.error:[30/Oct/2021:14:37:36] ENGINE Stopped thread 'SSDP_NOTIFY_THREAD'.
INFO:MPVRenderer:stoping mpv and mpv ipc
ERROR:MPVRenderer:sendCommand: 'NoneType' object has no attribute 'send_bytes'
ERROR:MPVRenderer:[Errno 10] No child processes
ERROR:MPVRenderer:mpv ipc socket start connect
ERROR:MPVRenderer:mpv ipc socket reconnecting: [WinError 2] 系统找不到指定的文件。
ERROR:SSDPServer:drop membership 192.168.31.30
ERROR:SSDPServer:drop membership 192.168.137.1
INFO:main:service_stop
INFO:cherrypy.error:[30/Oct/2021:14:37:37] ENGINE Stopped thread 'Autoreloader'.
INFO:cherrypy.error:[30/Oct/2021:14:37:37] ENGINE Removed handler for console events.
INFO:cherrypy.error:[30/Oct/2021:14:37:37] ENGINE Bus STOPPED
INFO:cherrypy.error:[30/Oct/2021:14:37:37] ENGINE Bus EXITING
INFO:cherrypy.error:[30/Oct/2021:14:37:37] ENGINE Waiting for child threads to terminate...
INFO:cherrypy.error:[30/Oct/2021:14:37:37] ENGINE Bus EXITED
INFO:cherrypy.error:[30/Oct/2021:14:37:37] ENGINE Waiting for thread MPV_STOP_SERVICE.
INFO:main:Service stopped
```

**Comment by xfangfang** [comment]
项目wiki中关于pip安装有详细的说明：https://github.com/xfangfang/Macast/wiki/Installation#pip

> You need to install MPV manually and configure it in the system PATH

**Comment by xfangfang** [comment]
@zqzess  您好，请问后续解决问题了吗？

**Comment by zqzess** [comment]
> @zqzess  您好，请问后续解决问题了吗？

解决了，谢谢

**Comment by xfangfang** [comment]
好的，那先关闭这个issue了，有问题欢迎随时开issue

**Comment by BBJG001** [comment]
我也遇到了相同的问题
`$ macast-cli
{'Additional_Interfaces': [], 'ApplicationPort': 45057, 'Blocked_Interfaces': [], 'CheckUpdate': 1, 'DLNA_FriendlyName': 'Macast(zydDebian)', 'DLNA_Renderer': 'Default', 'MenubarIcon': 0, 'PlayerHW': 1, 'PlayerPosition': 2, 'PlayerSize': 1, 'StartAtLogin': 0, 'USN': '648fa979-dcd7-49f1-ac61-bebe80857781'}
ERROR:SSDPServer:add membership 10.23.37.145
INFO:MPVRenderer:starting mpv and mpv ipc
INFO:MPVRenderer:mpv starting
INFO:cherrypy.error:[17/Dec/2021:14:26:14] ENGINE Started monitor thread 'SSDP_NOTIFY_THREAD'.
INFO:cherrypy.error:[17/Dec/2021:14:26:14] ENGINE Started monitor thread 'Autoreloader'.
INFO:cherrypy.error:[17/Dec/2021:14:26:14] ENGINE Bus STARTED
INFO:main:Server current run on port: 45057
ERROR:MPVRenderer:mpv ipc socket start connect
INFO:MPVRenderer:{'event': 'property-change', 'id': 1, 'name': 'volume', 'data': 100.0}
INFO:MPVRenderer:{'event': 'property-change', 'id': 3, 'name': 'pause', 'data': False}
INFO:MPVRenderer:{'event': 'property-change', 'id': 1, 'name': 'volume', 'data': 50.0}
INFO:cherrypy.access.139627468636800:10.23.37.15 - - [17/Dec/2021:14:26:44] "GET /description.xml HTTP/1.1" 200 1964 "" "Darwin/15.0.0, UPnP/1.1, MiniUPnPc/2.0"
INFO:cherrypy.access.139627468636800:10.23.37.15 - - [17/Dec/2021:14:26:44] "GET /description.xml HTTP/1.1" 200 1964 "" "Darwin/15.0.0, UPnP/1.1, MiniUPnPc/2.0"
INFO:cherrypy.access.139627468636800:10.23.37.15 - - [17/Dec/2021:14:26:44] "GET /description.xml HTTP/1.1" 200 1964 "" "Darwin/15.0.0, UPnP/1.1, MiniUPnPc/2.0"
INFO:cherrypy.access.139627468636800:10.23.37.15 - - [17/Dec/2021:14:26:44] "GET /description.xml HTTP/1.1" 200 1964 "" "Darwin/15.0.0, UPnP/1.1, MiniUPnPc/2.0"
INFO:cherrypy.access.139627468636800:10.23.37.15 - - [17/Dec/2021:14:26:44] "GET /description.xml HTTP/1.1" 200 1964 "" "Darwin/15.0.0, UPnP/1.1, MiniUPnPc/2.0"
INFO:cherrypy.access.139627468636800:10.23.37.15 - - [17/Dec/2021:14:26:44] "GET /description.xml HTTP/1.1" 200 1964 "" "Darwin/15.0.0, UPnP/1.1, MiniUPnPc/2.0"
ERROR:SSDPServer:drop membership 10.23.37.145
ERROR:SSDPServer:add membership 10.23.37.145
ERROR:SSDPServer:drop membership 10.23.37.145
ERROR:SSDPServer:add membership 10.23.37.145
ERROR:SSDPServer:drop membership 10.23.37.145
ERROR:SSDPServer:add membership 10.23.37.145`

之后会循环这个drop、add；
debian11

**Comment by BBJG001** [comment]
> > @zqzess  您好，请问后续解决问题了吗？
> 
> 解决了，谢谢

你好，请问这个问题要怎么解决啊

**Comment by xfangfang** [comment]
> > > @zqzess  您好，请问后续解决问题了吗？
> > 
> > 
> > 解决了，谢谢
> 
> 你好，请问这个问题要怎么解决啊

@BBJG001  您好，上面的log已经表示正常启动了，最后循环出现的drop和add 是在定时刷新本机ip，属于正常现象

**Comment by BBJG001** [comment]
> > > > @zqzess  您好，请问后续解决问题了吗？
> > > 
> > > 
> > > 解决了，谢谢
> > 
> > 
> > 你好，请问这个问题要怎么解决啊
> 
> @BBJG001 您好，上面的log已经表示正常启动了，最后循环出现的drop和add 是在定时刷新本机ip，属于正常现象

我看到它是一个Error的日志，还以为有问题

请问我想从电脑A投屏到电脑B，就是把B作为A的扩展屏这能做到么
主要是因为M1芯片的机器限制了扩展屏数量，常规方法不好操作

**Comment by xfangfang** [comment]
@BBJG001 可以看一看应用的介绍，Macast目前功能为dlna媒体投屏，主要负责接收显示媒体文件
